site_name: "Module tp-iterateurs"
site_author: "FIL-ASD"
copyright: "2015-2022, FIL-ASD, Univ. Lille"
theme:
  name: "material"
  logo: ulille.png
  palette:
    primary: purple

nav:
  - Rendu: index.md
  - Documentation: modules.md
  
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_source: yes
        paths: [src]
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://www.fil.univ-lille.fr/~salson/portail/mathjax_conf.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
